### ISSUE TITLE
unexpected results for <https://example.com>

### ISSUE THREAD

**Issue by dlangille** [vstelmakh/url-highlight#40]
This is my test sample.  The output for 3.0.1 and head is the same from what I can tell.

```
<?php
require __DIR__ . '/vendor/autoload.php';

use VStelmakh\UrlHighlight\UrlHighlight;

$urlHighlight = new UrlHighlight();
echo $urlHighlight->highlightUrls('1 - Hello, http://example.com.');
echo "\n";


echo $urlHighlight->highlightUrls('2 - this is email <dan@example.org>');
echo "\n";

echo $urlHighlight->highlightUrls('3 - this is email &lt;dan@example.org&gt;');
echo "\n";

echo $urlHighlight->highlightUrls('4 - this is URL  http://example.org/');
echo "\n";

echo $urlHighlight->highlightUrls('5 - this is URL <http://example.org/>');
echo "\n";

echo $urlHighlight->highlightUrls('6 - this is URL &lt;http://example.org/&gt;');
echo "\n";
```

This is the output:

```
[empty dan ~/tmp] % php testing.php
1 - Hello, <a href="http://example.com">http://example.com</a>.
2 - this is email <dan@example.org>
3 - this is email &<a href="mailto:lt;dan@example.org">lt;dan@example.org</a>&gt;
4 - this is URL  <a href="http://example.org/">http://example.org/</a>
5 - this is URL <http://example.org/>
6 - this is URL &lt;<a href="http://example.org/&gt">http://example.org/&gt</a>;
```

The problem areas are on lines 3, 5, and 6 of the output

* 3 -  The `mailto:` link has a misplaced `&` - it should be after the `mailto:`
* 5 - I expected the same output as line 4
* 6 - I attempted to get line 5 to work but I see that this is not the way

**Comment by vstelmakh** [comment]
Hi Dan :wave: 

Thank you for the report. Reproduction steps are really nice :+1: 

Long story short: this is expected behaviour.

<details>
  <summary>Long story</summary>

URLs enclosed by `<` and `>`, for example `<http://example.org/>` (case 2 and 5) - expected to be not highlighted. This is a prevention mechanism from potential “double” highlighting if link already an `a` tag: `<a href="http://example.org/">http://example.org/</a>`, or in cases like this: `<button data-link="http://example.com/">`. 

For the HTML page: `<http://example.org/>` - is not a valid code, as `<` and `>` should be encoded to htmlentities, to be displayed properly. Like: `&lt;http://example.org/&gt;`. Which leads to another problem - highlighting like in cases 3 and 6 from your example. Technically, highlighting works correctly, as `http://example.org/&gt` - is a valid url, and `;` is the punctuation after.
</details>

And there is a solution for this - escape HTML special characters ([htmlspecialchars](https://www.php.net/manual/en/function.htmlspecialchars.php)) before passing input to library and use [Encoder](https://github.com/vstelmakh/url-highlight#encoder) to let the library know that input is HTML encoded.

For example:
```php
require __DIR__ . '/vendor/autoload.php';

use VStelmakh\UrlHighlight\Encoder\HtmlSpecialcharsEncoder;
use VStelmakh\UrlHighlight\UrlHighlight;

$encoder = new HtmlSpecialcharsEncoder();
$urlHighlight = new UrlHighlight(null, null, $encoder);

$input = '3 - this is email <dan@example.org>';
$escaped = htmlspecialchars($input); // &lt;dan@example.org&gt;
echo $urlHighlight->highlightUrls($escaped); // 3 - this is email &lt;<a href="mailto:dan@example.org">dan@example.org</a>&gt;

$input = '6 - this is URL <http://example.org/>';
$escaped = htmlspecialchars($input); // &gt;6 - this is URL &lt;http://example.org/&gt;
echo $urlHighlight->highlightUrls($escaped); // 6 - this is URL &lt;<a href="http://example.org/">http://example.org/</a>&gt;
```

---

If, for some reason, your input is encoded more than just html special chars, use `HtmlEntitiesEncoder` encoder. But keep in mind, it's a bit slover as require more regex operations.

<details>
  <summary>Example using HtmlEntitiesEncoder, with all characters HTML encoded</summary>

```php
use VStelmakh\UrlHighlight\Encoder\HtmlEntitiesEncoder;
use VStelmakh\UrlHighlight\UrlHighlight;

//$urlHighlight = new UrlHighlight();
$encoder = new HtmlEntitiesEncoder();
$urlHighlight = new UrlHighlight(null, null, $encoder);

$escaped = '&#x45;&#x76;&#x65;&#x72;&#x79;&#x74;&#x68;&#x69;&#x6E;&#x67;&#x20;&#x61;&#x73;&#x20;&#x68;&#x74;&#x6D;&#x6C;&#x20;&#x65;&#x6E;&#x74;&#x69;&#x74;&#x69;&#x65;&#x73;&#x20;&#x3C;&#x65;&#x78;&#x61;&#x6D;&#x70;&#x6C;&#x65;&#x2E;&#x6F;&#x72;&#x67;&#x3E;'; // Everything as html entities <example.org>
echo $urlHighlight->highlightUrls($escaped); // &#x45;&#x76;&#x65;&#x72;&#x79;&#x74;&#x68;&#x69;&#x6E;&#x67;&#x20;&#x61;&#x73;&#x20;&#x68;&#x74;&#x6D;&#x6C;&#x20;&#x65;&#x6E;&#x74;&#x69;&#x74;&#x69;&#x65;&#x73;&#x20;&#x3C;<a href="http://example.org">&#x65;&#x78;&#x61;&#x6D;&#x70;&#x6C;&#x65;&#x2E;&#x6F;&#x72;&#x67;</a>&#x3E;
// which will be rendered in the browser as: 
// Everything as html entities <example.org>
//                         clickable ↑
```
</details>

---

Hope this helps. Please let me know if this is solving your issue :rocket:

**Comment by dlangille** [comment]
I think this is good. Thank you.
